name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore MyApp.sln

      - name: Build
        run: dotnet build MyApp.sln --no-restore

      - name: Test
        run: dotnet test MyApp.sln --no-build

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: Run Container (Test)
        run: docker run -d -p 8080:80 myapp